### ISSUE TITLE
IAM Role support

### ISSUE THREAD

**Issue by jjshoe** [krobertson/deb-s3#105]
It would be awesome if deb-s3 could use IAM roles for credentials.

**Comment by jjshoe** [comment]
http://docs.aws.amazon.com/AWSRubySDK/latest/AWS/Core/CredentialProviders/AssumeRoleProvider.html

**Comment by jjshoe** [comment]
The DefaultProvider claims to try this as a fallback in the Ruby SDK docs, but doesn't seem to be the case here.

**Comment by twmartin** [comment]
@jjshoe - I believe `deb-s3` will support authentication through IAM roles. I was running into difficulty during upload attempts before I realized that I needed to allow `s3:PutObjectAcl` in addition to `s3:PutObject` in my IAM role policy.

**Comment by gaieges** [comment]
I've had success with an instance role and a IAM policy behind that being able to upload to s3 using deb-s3.  

However, the one piece of feedback I would leave is to ensure that the `PutObjectAcl` requirement (and in general what a minimum IAM policy is needed for this) is included in documentation.  I spent a bit of time trying to figure out what the proper minimum policy needed to allow this to work was, before finding this thread (thanks @twmartin!).
