### ISSUE TITLE
Upgrade to AWS SDK v2

### ISSUE THREAD

**Issue by drusellers** [krobertson/deb-s3#120]
AWS SDK has released a v2 - while probably not critical would be nice to have this upgraded to v2+

**Comment by krobertson** [comment]
The V2 API is actually in master, I just need to get of my butt and release a new version. :smile:

**Comment by drusellers** [comment]
Dopeness!

**Comment by chadbean** [comment]
@krobertson how many 🍺 's will it take to get you to cut that release?

**Comment by krobertson** [comment]
@chadbean Done... sorry, I can be forgetful.
