### ISSUE TITLE
Please provide an example with the `--sign` option

### ISSUE THREAD

**Issue by drusellers** [krobertson/deb-s3#121]
Its not clear to me if I use an EC2 Key or a key on my box. A key on my box makes the most sense. But I just have the one ssh key at the moment. sounds like I may need a new one.

**Comment by krobertson** [comment]
Sure, I'll update. 

The signing is with GPG. If you don't give a param, GPG will just select a key to use. Otherwise, to specify the key you provide it's fingerprint/key ID.

**Comment by drusellers** [comment]
Took me a while to figure it out but I got it. Just new to the Debian
workflow. :)

**Comment by drnic** [comment]
An example from our CI for https://apt.starkandwayne.com is:

* setup GPG key in local CI container https://github.com/starkandwayne/homebrew-cf/blob/master/ci/scripts/create-debian-pkg-from-binary.sh#L22-L34
```
mkdir -p certs
echo "${GPG_ID:?required}" > certs/id
echo "${GPG_PUBLIC_KEY:?required}" > certs/public.key
set +x
echo "${GPG_PRIVATE_KEY:?required}" > certs/private.key
[ -n "$DEBUG" ] && set -x

echo ">> Setup GPG public key"
gpg --import certs/public.key
echo ">> Setup GPG private key"
gpg --allow-secret-key-import --import certs/private.key
echo ">> List keys"
gpg --list-secret-keys
```

* Run `deb-s3 upload --sign id`
```
deb-s3 upload "${DEBIAN_FILE}" --bucket "${RELEASE_BUCKET}" --sign $(cat certs/id)
```

**Comment by krobertson** [comment]
Updated the help text and readme to clarify its a GPG key, and how to specify.
