### ISSUE TITLE
InRelease should be generated by default

### ISSUE THREAD

**Issue by magnetik** [krobertson/deb-s3#137]
Hi,

The debian repository format states that the `InRelease` should be present, and the Release file should be present for older client.

At the moment, it's generated only for the codenames "xenial", "jessie" and "stretch". Shouldn't this be the default behavior? 

Thanks for this gem :)

**Comment by magnetik** [comment]
@krobertson Any input on this? thanks :)

**Comment by agimenez** [comment]
+1 on this, this should be nice to be applied

**Comment by magnetik** [comment]
He merged a PR made after this one, not sure why this one got no attention so far. Let's be patient ^^
