### ISSUE TITLE
--gpg-options does not work

### ISSUE THREAD

**Issue by rchekaluk** [krobertson/deb-s3#25]
Trying to use --gpg-options produces an error like this:

```
$ deb-s3 upload --bucket redacted --arch amd64 --component redacted --codename production --access-key redacted --secret-key redacted --sign=redacted --gpg-options="--no-tty" redacted_162_all.deb 
!! File '--no-tty' doesn't exist
```

Inserting a little debug output shows that function upload is being passed an incorrect set of values for *files; is Thor incorrectly parsing the command-line?

```
["--no-tty", "redacted_all.deb"]
```

**Comment by sensedeep** [comment]
I had to use:

```
--gpg-options="\-\-batch \-\-no-use-agent \-\-passphrase-file gpg.keys"
````

**Comment by wangii** [comment]
which version of gpg were you guys using? it doesn't work any more.
