### ISSUE TITLE
Filenames with versions are wrong

### ISSUE THREAD

**Issue by mzupan** [krobertson/deb-s3#44]
If the filename has a + in it which some packages use in their versions deb-s3 writes the packages wrong since it look like it switches the + with the urlencoded version

see the following

```
Package: salt-cloud
Version: 2014.1.7+ds-1trusty1
License: unknown
Vendor: none
Architecture: all
Maintainer: Joe Healy <joehealy@gmail.com>
Installed-Size: 99
Depends: python:any, salt-common (= 2014.1.7+ds-1trusty1), sshpass
Section: admin
Priority: extra
Homepage: http://saltstack.org/
Filename: pool/s/sa/salt-cloud_2014.1.7%2Bds-1trusty1_all.deb
```

It was causing apt-get to 403 trying to get the file

```
Err http://company-apt-trusty.s3.amazonaws.com/ stable/main salt-common all 2014.1.7+ds-1trusty1
  403  Forbidden
Fetched 6,041 kB in 4s (1,311 kB/s)
E: Failed to fetch http://company-apt-trusty.s3.amazonaws.com/pool/s/sa/salt-minion_2014.1.7%2Bds-1trusty1_all.deb  403  Forbidden

E: Failed to fetch http://company-apt-trusty.s3.amazonaws.com/pool/s/sa/salt-common_2014.1.7%2Bds-1trusty1_all.deb  403  Forbidden

```

The file on the s3 bucket had the + in there

If I renamed the file to remove the + things worked

**Comment by jnankin** [comment]
I opened a PR for this awhile back, any reason it's not being accepted?

**Comment by BrianAdams** [comment]
I just tried with 7.1 and I am still seeing the the Filename in the actual repo files being URL encoded which it should not be.


From: http://deb-repo.rov.com/dists/pre-release/debian/binary-armhf/Packages
```
...

Package: rov-avrdude
Version: 1:5.11.1-1~24.ad04c42
License: unknown
Vendor: @04d7752423d9
Architecture: armhf
Maintainer: info@rov.com
Installed-Size: 1478
Section: default
Priority: extra
Homepage: http://example.com/no-uri-given
Filename: pool/o/op/rov-avrdude_1%3A5.11.1-1~24.ad04c42_armhf.deb
Size: 482248
SHA1: d9a8834add57756de41eb68092471d6b3b3bfcff
SHA256: 542ae3f40f78ed722401891302867c10e258c45b67fe046e425e422ca3ec7a16
MD5sum: c023e18f2fea9b6d2620169948d09db0
Description: ROV avrdude package
```
Note the Filename: pool/o/op/rov-avrdude_1**%3A**5.11.1-1~24.ad04c42_armhf.deb above

I did confirm that #45 looks to be merged in master.  Any ideas?

**Comment by BrianAdams** [comment]
I fixed the last issue I had in PR #77

**Comment by rmoriz** [comment]
still and issue with `~`, e.g.  ` 3.4.1-2~bpo80+1`

**Comment by krobertson** [comment]
This iasueiasue has pingponged. I've had bugs filed with it both ways. I'm planning on just changing it to strip the problem characters from the filename.

**Comment by sigil66** [comment]
The root issue is  S3 mangling + -> " ". https://github.com/sigil66/apt-transport-s3/blob/master/src/s3%2Bhttp.cc#L686

I hate this issue so very much.
