### ISSUE TITLE
Copy Command

### ISSUE THREAD

**Issue by zoltrain** [krobertson/deb-s3#53]
Something that we've been needing for a while is package promotion. Being able to move it from one distribution/component to another.

This way we can build against a commit, and promote that package up to different repositories vs having to publish it to multiple repositories. Since the GPG, file management has already been done in deb-s3 it makes sense to me to add this feature here.

It's also something that would save on upload time, since you can do an internal S3 copy that doesn't leave the AWS network.

Happy to start plugging away at it, just thought I'd put it up for discussion here, in terms of how the command should look.

deb-s3 cp "package_name/path" "package_name/path" where path = distribution/component elements.
e.g.
deb-s3 cp redis2.8.1 stable/main/staging stable/main/production

**Comment by krobertson** [comment]
Cleaning up some old issues... `deb-s3 copy` was added in 0.7.0.
