### ISSUE TITLE
Package overwrite in pool between distribution

### ISSUE THREAD

**Issue by guilhem** [krobertson/deb-s3#55]
In our case we are building package for 3 distributions: wheezy, precise, trusty.

Packages have same version.

When we are uploading them, everything is ok in every "package" file.. but bad things happen in `pool` directory: only last file uploaded take place and every distribution other distributions point to this one...

**Comment by rmoriz** [comment]
same issue here :(

**Comment by hertzsprung** [comment]
This is going to be a problem for me.  Rather than going into `pool/`, shouldn't binary .debs be put in the `dist/` tree alongside the Packages files?
