### ISSUE TITLE
AWS::S3::Errors::Forbidden

### ISSUE THREAD

**Issue by im905513** [krobertson/deb-s3#66]
I use deb-s3 got the message in below. What happen about this?

I don't change any setting , it can be work normal before, but can not work now
---------------------------------------------------------------------------------------
Retrieving existing manifests
/var/lib/gems/1.9.1/gems/aws-sdk-1.40.2/lib/aws/core/client.rb:375:in `return_or_raise': AWS::S3::Errors::Forbidden (AWS::S3::Errors::Forbidden)
        from /var/lib/gems/1.9.1/gems/aws-sdk-1.40.2/lib/aws/core/client.rb:478:in `client_request'
        from (eval):3:in `head_object'
        from /var/lib/gems/1.9.1/gems/aws-sdk-1.40.2/lib/aws/s3/s3_object.rb:293:in `head'
        from /var/lib/gems/1.9.1/gems/aws-sdk-1.40.2/lib/aws/s3/s3_object.rb:270:in `exists?'
        from /var/lib/gems/1.9.1/gems/deb-s3-0.6.2/lib/deb/s3/utils.rb:55:in `s3_exists?'
        from /var/lib/gems/1.9.1/gems/deb-s3-0.6.2/lib/deb/s3/utils.rb:59:in `s3_read'
        from /var/lib/gems/1.9.1/gems/deb-s3-0.6.2/lib/deb/s3/release.rb:23:in `retrieve'
        from /var/lib/gems/1.9.1/gems/deb-s3-0.6.2/lib/deb/s3/cli.rb:116:in `upload'
        from /var/lib/gems/1.9.1/gems/thor-0.18.1/lib/thor/command.rb:27:in `run'
        from /var/lib/gems/1.9.1/gems/thor-0.18.1/lib/thor/invocation.rb:120:in `invoke_command'
        from /var/lib/gems/1.9.1/gems/thor-0.18.1/lib/thor.rb:363:in `dispatch'
        from /var/lib/gems/1.9.1/gems/thor-0.18.1/lib/thor/base.rb:439:in `start'
        from /var/lib/gems/1.9.1/gems/deb-s3-0.6.2/bin/deb-s3:8:in `<top (required)>'
        from /usr/local/bin/deb-s3:19:in `load'
        from /usr/local/bin/deb-s3:19:in `<main>'

**Comment by drusellers** [comment]
Do you have S3 permissions to write?

**Comment by rmldsky** [comment]
I believe this issue could be close. Reporter did not provide any further reply, plus it looks like permissions issues.

**Comment by securityvoid** [comment]
What does the policy need to look like for the permissions to work?

I've got the following and I'm getting this same forbidden message:
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Sid": "Stmt1483565451843",
            "Action": [
                "s3:DeleteObject",
                "s3:DeleteObjectacl",
                "s3:GetObject",
                "s3:ListBucket",
                "s3:PutObject",
                "s3:PutObjectacl"
            ],
            "Effect": "Allow",
            "Resource": "arn:aws:s3:::MY_BUCKET_NAME/*"
        }
    ]
}

**Comment by sholsapp** [comment]
Same error with all permissions allowed on bucket.

**Comment by sholsapp** [comment]
@securityvoid I figured this out, and figured I'd leave a note here for the next guy. Besides the permissions you mentioned here, you also need to add the ListBucket permission to the bucket.
