### ISSUE TITLE
Add support for uploading debian packages to S3 using AWS CodeDeploy

### ISSUE THREAD

**Issue by thedrow** [krobertson/deb-s3#70]
CodeDeploy triggers more actions when deploying a build artifact. It uploads them to S3 which means it is within the scope of the project.
If you could provide an option to use it to upload to debian packages to S3 I'd be happy to donate a 100$ to you or to a charity of your choosing.

**Comment by krobertson** [comment]
I haven't used AWS CodeDeploy at all. Do you have any ideas on how it would work from the user's perspective? Like have deb-s3 kick off a CodeDeploy event to do everything end to end? I'll try and look at the API docs later to see what it actually supports running and what it supports as parameters.

**Comment by thedrow** [comment]
I haven't done it myself yet but I'm planning to.
I know that the deployed build artifact ends up on S3 and that AWS CodeDeploy can trigger CM tools in order to update.
