### ISSUE TITLE
Packages now download when trying to view in a browser

### ISSUE THREAD

**Issue by BrianAdams** [krobertson/deb-s3#78]
It used to be you could go to the url for a package, say
`dists/master/debian/binary-armhf/Packages` and the browser would load the XML for you to view in the browser.  

Instead, as of version 7.1, the system now causes the browser to download the file content.  Is this change by design?  If not, I assume the mime type got changes somewhere, if you can give a hint on where to look I can try fixing it.

**Comment by krobertson** [comment]
Fixed in #83
