### ISSUE TITLE
Go with newer(-est) version of aws-sdk in dependencies?

### ISSUE THREAD

**Issue by rmldsky** [krobertson/deb-s3#80]
Hi,
Currently the gem depends on `"aws-sdk", "~> 1.18"` is there a chance to bump it up to recent version of `aws-sdk`? I could see in the commit history you did change the dependency once already but reverted it back the next day. Where there any problems with it? Does it involve a lot of code changes of `deb-s3` itself? Is this planned anytime soon?

Thanks!

**Comment by rmldsky** [comment]
...or if this requires too much work, change the dependency to `aws-sdk-v1` According to AWS [documentation](http://ruby.awsblog.com/post/Tx2NJE86FP0HHXX/Announcing-V2-of-the-AWS-SDK-for-Ruby) this is a recommended way to use both version in one application.

**Comment by rmldsky** [comment]
I've submitted a pull request (#81) if this is something you might consider doing.

**Comment by krobertson** [comment]
I had started updating to the latest gem back in February, but it was right as I was going to push out a new release and realized it was more than just a drop in and fix a few things change. I haven't touched it since then though. I pushed the branch up, it is `update-to-aws-sdk-2`.

**Comment by rmldsky** [comment]
Hm, I believe I read your comment in another issue, in which you stated you would like to still support Ruby 1.8.7. From what I have found out it seems both `aws-sdk` (which now defaults to 2) and `aws-sdk-v1` (even the lowest version) both pull `nokogiri` as a dependency in a version which fails building on 1.8.7 (see my pull request details and failed build on Travis). I do not have enough knowledge to know if this could be overcome in order to still support Ruby 1.8.7.

Quick win for people who would like to use latest aws-sdk in their application and use deb-s3 without much change in it, would be going for `aws-sdk-v1` in deb-s3 dependency. But as mentioned this would harm people using deb-s3 on 1.8.7. Also going forward with upgrading `aws-sdk` in deb-s3 would also harm them... :cry:
